# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('desc', models.CharField(default='商品描述', max_length=200, verbose_name='描述')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/img/good_type', verbose_name='图片')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
    ]
