# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-24 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('unit', models.CharField(default='500g', max_length=20, verbose_name='单位')),
                ('desc', models.CharField(max_length=1000, verbose_name='描述')),
                ('detail', models.CharField(default='商品详情', max_length=2000, verbose_name='商品详情')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/images/goods', verbose_name='商品照片')),
                ('isDelete', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.GoodsType')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
